### Sync
POST {{base}}/course/sync HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

{
  "courseId": "5d272ca5e3f20d3b3e9930e9",
  "last": 0,
  "DDDD": 1
}

### UCMap
POST {{base}}/course/ucmap HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

{
  "courseId": "5d272ca5e3f20d3b3e9930e9",
  "last": 0
}