@course = 5d272ca5e3f20d3b3e9930e9

### Sync
POST {{base}}/file/sync HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}
x-course-id: {{course}}

{
  "last": 0
}

### New
POST {{base}}/file/new HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}
x-course-id: {{course}}

{
  "path": "/test",
  "tags": ["1"],
  "versions": [
    {
      "name": "default",
      "hash": "1a2b3c"
    }
  ]
}