### Sync
POST {{base}}/user/sync HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

{
  "ids": ["5d26ee56b39455e08cf1c428"],
  "last": 0
}

### List
GET {{base}}/user/list HTTP/1.1
x-access-token: {{token}}

### password
POST {{base}}/user/pass HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

{
  "old": "123456",
  "new": "123456"
}

### profile
POST {{base}}/user/prof HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

{
  "email": "admin@zhangzisu.cn"
}