@base = http://localhost:3000
@token = a5fc32209772651b711da0c195064b75063b042367e09fe82ca724e37c4d0701

### Sync
POST {{base}}/user/sync HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

{
  "ids": ["5d26ee56b39455e08cf1c428"],
  "last": 1562832920705
}

### List
GET {{base}}/user/list HTTP/1.1
x-access-token: {{token}}

### password
POST {{base}}/user/pass HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

{
  "id": "5d26ee56b39455e08cf1c428",
  "pass": "123456",
  "newpass": "123456"
}