version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    restart: always

  hexagon:
    image: zhangzisu/hexagon:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://mongo:27017/hex
      REDIS_URL: redis://redis